#pragma once

#define STORM_BUILD_WATERMARK unknown
#define STORM_STRINGIFY_EXPAND_(x) #x
#define STORM_STRINGIFY_(x) STORM_STRINGIFY_EXPAND_(x)
#define STORM_BUILD_WATERMARK_STRING STORM_STRINGIFY_(STORM_BUILD_WATERMARK)
