add_subdirectory(animals)
add_subdirectory(animation)
add_subdirectory(ball_splash)
add_subdirectory(battle_interface)
add_subdirectory(blade)
add_subdirectory(blot)
add_subdirectory(collide)
add_subdirectory(config)
add_subdirectory(core)
add_subdirectory(diagnostics)
add_subdirectory(dialog)
add_subdirectory(filesystem)
add_subdirectory(geometry)
add_subdirectory(input)
add_subdirectory(island)
add_subdirectory(lighter)
add_subdirectory(location)
add_subdirectory(locator)
add_subdirectory(mast)
add_subdirectory(math)
add_subdirectory(model)
add_subdirectory(particles)
add_subdirectory(pcs_controls)
add_subdirectory(renderer)
add_subdirectory(rigging)
add_subdirectory(sailors)
add_subdirectory(script_library)
add_subdirectory(sea)
add_subdirectory(sea_ai)
add_subdirectory(sea_cameras)
add_subdirectory(sea_creatures)
add_subdirectory(sea_foam)
add_subdirectory(sea_operator)
add_subdirectory(shadow)
add_subdirectory(shared_headers)
add_subdirectory(ship)
add_subdirectory(sink_effect)
add_subdirectory(sound)
add_subdirectory(sound_service)
add_subdirectory(steam_api)
add_subdirectory(teleport)
add_subdirectory(tornado)
add_subdirectory(touch)
add_subdirectory(util)
add_subdirectory(water_rings)
add_subdirectory(weather)
add_subdirectory(window)
add_subdirectory(worldmap)
add_subdirectory(xinterface)
