name: CI Linux

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - '*.md'

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.1
        with:
          # skip concurrent jobs if they are on the same thing
          concurrent_skipping: 'same_content'
          # never skip PR, release or manual/scheduled runs
          do_not_skip: '["pull_request", "release", "workflow_dispatch", "schedule"]'

  build-linux:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [ Debug ]
    name: 'linux [${{matrix.configuration}}]'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install libs
        run: |
          sudo apt-get update && sudo apt-get install  build-essential make meson libstdc++-13-dev libvulkan-dev glslang-tools libgl-dev libegl-dev libcurlpp-dev zlib1g-dev libvorbis-dev libogg-dev libopenal-dev libd3dadapter9-mesa-dev libxcb-present-dev libxcb-dri3-dev libx11-xcb-dev pkg-config gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev
      - name: Clone SDL3
        run: |
          git clone -b release-3.2.16 https://github.com/libsdl-org/SDL.git
      - name: Install SDL3
        run: |
          export CC=clang-18
          export CXX=clang++-18
          cmake -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.configuration}} -S . -B build/${{matrix.configuration }}
          cmake --build build/${{matrix.configuration}}
          sudo cmake --install build/${{matrix.configuration}}
        working-directory: SDL
      - name: Configure with CMake
        run: |
          export CC=clang-18
          export CXX=clang++-18
          ${CXX} --version
          cmake --preset=${{ matrix.configuration }}
      - name: Build
        run: cmake --build --preset=${{ matrix.configuration }}
